runmode: debug                  # 开发模式, debug, release, test
addr: :8080                     # HTTP绑定端口
name: api-auth                # API Server的名字
url: http://127.0.0.1:8080      # pingServer函数请求的API服务器的ip:port
max_ping_count: 10              # pingServer函数try的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5    #用于 JWT Token加密的Secret
db:
  name: db_apiserver            # 支持嵌套，如这里对应环境变量名为：MYAPP_DB_NAME
  addr: 127.0.0.1:3306
  username: alan
  password: M7auDkfa            # 密码，如果共享的话注意避免泄漏，这里的是我本地的数据库，不支持公网访问所以可以明文

# log:                            # 日志配置
#   writers: file,stdout          # 输出位置，有两个可选项：file 和 stdout。file将日志记录到 logger_file 指定的日志文件中;stdout 会将日志输出到标准输出，也可以两者同时选择。
#   logger_level: DEBUG           # 日志级别，DEBUG、INFO、WARN、ERROR、FATAL
#   logger_file: log/apiserver.log  # 日志文件(相对位置或者绝对位置)
#   log_format_text: false        # 日志的输出格式，JSON 或者 plaintext，true 会输出成 JSON 格式，false 会输出成非 JSON 格式
#   rollingPolicy: size           # 日志轮转维度，可选的有 daily 和 size（根据天或大小进行转存）
#   # log_rotate_date: 1            # rotate 转存时间（单位：天），配 合rollingPolicy: daily 使用
#   log_rotate_size: 1            # rotate 转存大小（单位：MB），配合 rollingPolicy: size 使用
#   log_backup_count: 7           # 当日志文件达到转存标准时，log 系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数
